library(DBI)
library(RSQLite)
library(tidyverse)
library(storr)

db <- dbConnect(SQLite(), "data/corpus.sqlite3", flags = SQLITE_RO)
dbExecute(db, "PRAGMA foreign_keys = ON")
st <- storr_dbi("storr_data", "storr_keys", db, binary = TRUE)

bigrams <- tbl(db, "bigrams")
unigrams <- tbl(db, "unigrams")
document_unigram <- tbl(db, "document_unigram")
document_bigram <- tbl(db, "document_bigram")
documents <- tbl(db, "documents")
document_metadata <- tbl(db, "document_metadata")
corpora <- tbl(db, "corpus")
corpus_document <- tbl(db, "corpus_document")
corpus_rdata <- tbl(db, "corpus_rdata")
